ARCH=$1
PREFIX=$2
rootfs=$3
dtbfile=$4
output=$5

# uImage is not generated by default. Do it here.
#
LOADADDR=0x80008000 make ARCH=${ARCH} CROSS_COMPILE=${PREFIX} uImage >/dev/null 2>&1
if [ $? -ne 0 ]
then
    exit 1
fi

progdir=$(cd $(dirname $0); pwd)

/opt/buildbot/bin/mksdimage.sh -s 256 \
	-m ${progdir}/MLO.2011.9 -u ${progdir}/u-boot.bin.2011.9 \
	-b ${progdir}/boot.cmd \
	-r ${rootfs} -d ${dtbfile} \
	-k arch/arm/boot/uImage  \
	${output}
